### ISSUE TITLE
在 Windows CMD 中无法显示二维码，字符集编码有问题？

### ISSUE THREAD

**Issue by solarcellsky** [7sDream/pyqart#1]
C:\Users\Solar\Desktop>pyqr "Hello World"
Traceback (most recent call last):
  File "c:\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35-32\Scripts\pyqr.exe__main__.py", line 9, in <module>
  File "c:\python35-32\lib\site-packages\pyqart\qr_entry.py", line 79, in main
    QrStringPrinter.print(painter, True)
  File "c:\python35-32\lib\site-packages\pyqart\qr\printer\string_printer.py", line 44, in print
    print(string)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2580' in position 1: illegal multibyte sequence

**Comment by 7sDream** [comment]
Windows 环境还没测试过，因为用来在终端输出二维码的那个字符是 4个 特殊字符，GBK 可能显示不出来。

你参考[这个链接](http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how)里的方法试试先，看看能不能行……

**Comment by solarcellsky** [comment]
我加上参数貌似可以用了 :)
